#!/bin/sh

set -ex

# Let integration start containerd daemon
systemctl stop containerd
systemctl status containerd || true

dh_auto_configure -O--buildsystem=golang -O--builddirectory=_build

# build and make runc-fp available
DH_GOLANG_BUILDPKG=github.com/containerd/containerd/integration/failpoint/cmd/runc-fp \
    dh_auto_build -O--buildsystem=golang -O--builddirectory=_build

cp -v _build/bin/runc-fp /usr/local/bin
PATH=$(readlink -f _build/bin):$PATH
export PATH

# overlayfs not work in lxc
find _build/ -name snapshotter_default_linux.go -exec sed -i 's|DefaultSnapshotter = "overlayfs"|DefaultSnapshotter = "native"|g' {} +

DH_GOLANG_BUILDPKG=github.com/containerd/containerd/integration/client \
  dh_auto_test -O--buildsystem=golang -O--builddirectory=_build -- -c

# criu no permission in lxc testbed
./_build/client.test -test.v -test.root
